// website/components/hero-section.tsx
"use client"

/**
 * Hero Section — Apple Keynote 风格
 *
 * 设计理念:
 * - 全屏沉浸式，Apple 产品页的 "Keynote" 感
 * - Logo 以原始宽高比展示，不再被裁切
 * - 巨型标题，3:1 的标题/正文比例
 * - 单一主 CTA，次级为文字链接
 * - 数据指标用 Apple 的 "specs bar" 风格
 * - 左右两侧添加 PCB 主题装饰元素作为视觉锚点
 */
import Image from "next/image"
import { motion } from "framer-motion"
import { ChevronRight } from "lucide-react"
import { NumberTicker } from "./number-ticker"

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.3,
    },
  },
}

const itemVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.7, ease: [0.16, 1, 0.3, 1] },
  },
}

// PCB 装饰组件
function PcbDecoration({ side }: { side: "left" | "right" }) {
  const mirror = side === "left" ? "" : "scaleX(-1)"
  return (
    <div
      className={`absolute top-1/2 -translate-y-1/2 hidden xl:block pointer-events-none ${side === "left" ? "left-8" : "right-8"}`}
      style={{ transform: `${mirror} translateY(-50%)` }}
    >
      <svg
        width="160"
        height="400"
        viewBox="0 0 160 400"
        fill="none"
        className="opacity-20"
      >
        {/* 主走线 */}
        <path
          d="M 10 50 L 80 50 L 80 120 L 150 120"
          stroke="#c9944a"
          strokeWidth="1.5"
        />
        <path
          d="M 10 150 L 60 150 L 60 220 L 130 220"
          stroke="#c9944a"
          strokeWidth="1.5"
        />
        <path
          d="M 10 250 L 100 250 L 100 320 L 150 320"
          stroke="#3d8b5e"
          strokeWidth="1.5"
        />
        <path
          d="M 10 350 L 70 350 L 70 380 L 140 380"
          stroke="#c9944a"
          strokeWidth="1.5"
        />
        {/* 元件节点 */}
        <rect x="0" y="40" width="20" height="20" rx="2" stroke="#c9944a" strokeWidth="1" fill="none" />
        <rect x="130" y="110" width="20" height="20" rx="2" stroke="#c9944a" strokeWidth="1" fill="none" />
        <circle cx="80" cy="120" r="4" fill="#c9944a" />
        <circle cx="60" cy="150" r="4" fill="#c9944a" />
        <circle cx="60" cy="220" r="4" fill="#c9944a" />
        <rect x="40" y="210" width="40" height="20" rx="2" stroke="#3d8b5e" strokeWidth="1" fill="none" />
        <circle cx="100" cy="250" r="4" fill="#3d8b5e" />
        <circle cx="100" cy="320" r="4" fill="#3d8b5e" />
        <rect x="120" y="310" width="20" height="20" rx="2" stroke="#c9944a" strokeWidth="1" fill="none" />
        <circle cx="70" cy="350" r="4" fill="#c9944a" />
        <circle cx="70" cy="380" r="4" fill="#c9944a" />
        {/* 二极管符号 */}
        <line x1="130" y1="380" x2="155" y2="380" stroke="#c9944a" strokeWidth="1" />
        <polygon points="148,376 155,380 148,384" fill="#c9944a" />
      </svg>
    </div>
  )
}

export function HeroSection() {
  return (
    <section className="relative flex min-h-screen items-center justify-center overflow-hidden">
      {/* 背景 — Apple 式纯黑 + 微妙光晕 + PCB 网格 */}
      <div className="absolute inset-0 bg-background" />
      <div
        className="absolute inset-0"
        style={{
          background: `
            radial-gradient(ellipse 70% 50% at 50% 45%, rgba(201, 148, 74, 0.10) 0%, transparent 65%),
            radial-gradient(ellipse 40% 30% at 50% 50%, rgba(61, 139, 94, 0.04) 0%, transparent 50%)
          `,
        }}
      />
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage: `
            linear-gradient(rgba(201, 148, 74, 0.3) 1px, transparent 1px),
            linear-gradient(90deg, rgba(201, 148, 74, 0.3) 1px, transparent 1px)
          `,
          backgroundSize: '60px 60px',
        }}
      />

      {/* PCB 装饰 — 左右两侧 */}
      <PcbDecoration side="left" />
      <PcbDecoration side="right" />

      <motion.div
        className="relative z-10 mx-auto max-w-5xl px-6 text-center"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {/* 品牌 Logo — 原始宽高比，大尺寸展示 */}
        <motion.div variants={itemVariants} className="mb-10 flex justify-center">
          <Image
            src={`${process.env.NODE_ENV === 'production' ? '/summer-hardware-projects' : ''}/logo.png`}
            alt="多维国际教育"
            width={280}
            height={68}
            className="h-16 sm:h-20 md:h-24 w-auto object-contain opacity-90"
            priority
          />
        </motion.div>

        {/* 主标题 — 全白无双色 */}
        <motion.h1
          variants={itemVariants}
          className="text-hero font-bold leading-[1.05] tracking-tight text-text-primary"
        >
          从零开始，亲手打造
          <br />
          9 个真实硬件项目
        </motion.h1>

        {/* 副标题 — 苹果的 tagline 风格 */}
        <motion.p
          variants={itemVariants}
          className="mt-6 text-lg sm:text-xl text-text-secondary/70 font-light max-w-2xl mx-auto leading-relaxed"
        >
          高中生暑期硬件实践课程
        </motion.p>

        {/* CTA */}
        <motion.div
          variants={itemVariants}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <a
            href="#projects"
            className="group inline-flex items-center justify-center gap-2 rounded-full bg-accent-primary px-8 py-3.5 text-[15px] font-semibold text-white transition-all duration-300 hover:bg-accent-primary/90 hover:shadow-lg hover:shadow-accent-primary/20"
          >
            查看项目
            <ChevronRight size={16} className="transition-transform duration-200 group-hover:translate-x-0.5" />
          </a>
          <a
            href="#value-props"
            className="inline-flex items-center justify-center gap-1.5 text-[15px] font-medium text-text-secondary transition-colors duration-200 hover:text-accent-primary"
          >
            了解更多
          </a>
        </motion.div>

        {/* 移动端精简版数据指标 */}
        <motion.div
          variants={itemVariants}
          className="mt-10 flex sm:hidden items-center justify-center gap-4 text-[12px] text-text-tertiary"
        >
          <span className="font-mono"><span className="accent-text font-semibold">9</span> 项目</span>
          <span className="text-white/[0.12]">·</span>
          <span className="font-mono"><span className="accent-text font-semibold">10–20</span> 天</span>
          <span className="text-white/[0.12]">·</span>
          <span className="font-mono"><span className="accent-text font-semibold">≤¥500</span> 套</span>
        </motion.div>

        {/* 桌面端 specs bar */}
        <motion.div
          variants={itemVariants}
          className="mt-16 sm:mt-20 hidden sm:flex items-center justify-center gap-10 sm:gap-16"
        >
          <div className="text-center">
            <div className="text-4xl sm:text-5xl font-bold accent-text tabular-nums font-mono tracking-tight">
              <NumberTicker value={9} />
            </div>
            <p className="mt-2 text-xs text-text-tertiary uppercase tracking-widest font-medium">
              项目
            </p>
          </div>
          <div className="h-10 w-px bg-white/[0.12]" />
          <div className="text-center">
            <div className="text-4xl sm:text-5xl font-bold accent-text tabular-nums font-mono tracking-tight">
              <NumberTicker value={20} prefix="10–" />
            </div>
            <p className="mt-2 text-xs text-text-tertiary uppercase tracking-widest font-medium">
              天
            </p>
          </div>
          <div className="h-10 w-px bg-white/[0.12]" />
          <div className="text-center">
            <div className="text-4xl sm:text-5xl font-bold accent-text tabular-nums font-mono tracking-tight">
              <NumberTicker value={500} prefix="≤¥" />
            </div>
            <p className="mt-2 text-xs text-text-tertiary uppercase tracking-widest font-medium">
              每套
            </p>
          </div>
        </motion.div>
      </motion.div>
    </section>
  )
}

// website/components/HeroSection.vue
<template>
  <section ref="sectionRef" class="relative flex h-screen items-center justify-center overflow-hidden">
    <!-- Background layers (parallax) -->
    <div ref="bgLayer1" class="absolute inset-0 bg-background" />
    <div ref="bgLayer2" class="absolute inset-0" style="background: radial-gradient(ellipse 70% 55% at 50% 40%, rgba(255,154,118,0.10) 0%, transparent 70%), radial-gradient(ellipse 40% 35% at 55% 60%, rgba(255,107,107,0.05) 0%, transparent 60%); animation: gradientShift 8s ease infinite;" />
    <!-- Faint grid texture -->
    <div ref="bgLayer3" class="absolute inset-0 opacity-[0.015]" style="background-image: linear-gradient(rgba(255,154,118,0.22) 1px, transparent 1px), linear-gradient(90deg, rgba(255,154,118,0.22) 1px, transparent 1px); background-size: 80px 80px;" />
    <!-- Noise texture overlay -->
    <div class="pointer-events-none absolute inset-0 noise opacity-[0.015]" />

    <!-- Content -->
    <div class="relative z-10 mx-auto max-w-5xl px-6 text-center">
      <!-- Eyebrow -->
      <div ref="eyebrowRef" class="mb-6">
        <span class="eyebrow inline-flex items-center rounded-full px-4 py-1.5" style="background: linear-gradient(135deg, rgba(255,154,118,0.12), rgba(255,107,107,0.08));">2026 暑期</span>
      </div>

      <!-- Main title — animated reveal -->
      <h1 ref="titleRef" class="text-hero font-extrabold tracking-tight text-text-primary">
        <span class="block" data-split-line>从零开始</span>
        <span class="block" data-split-line>亲手打造 9 个真实硬件项目</span>
      </h1>

      <!-- Subtitle -->
      <p ref="subtitleRef" class="mt-8 text-xl sm:text-2xl text-text-secondary/80 font-normal max-w-xl mx-auto leading-relaxed">
        高中生暑期硬件实践课程
      </p>

      <!-- CTAs -->
      <div ref="ctaRef" class="mt-12 flex flex-col sm:flex-row items-center justify-center gap-5">
        <a
          ref="ctaBtnRef"
          href="#projects"
          class="magnetic-btn group relative inline-flex items-center justify-center gap-2.5 rounded-full px-9 py-4 text-[15px] font-semibold text-white overflow-hidden transition-shadow duration-300 hover:shadow-glow-strong"
          style="background: linear-gradient(135deg, #ff9a76, #ff6b6b);"
        >
          <span class="relative z-10">查看项目</span>
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="relative z-10 transition-transform duration-300 group-hover:translate-x-0.5"><path d="m9 18 6-6-6-6"/></svg>
          <!-- Inner glow on hover -->
          <span class="absolute inset-0 rounded-full opacity-0 transition-opacity duration-300 group-hover:opacity-100" style="background: radial-gradient(circle at 50% 50%, rgba(255,255,255,0.15), transparent 70%);" />
        </a>
        <a href="#value-props" class="text-[15px] font-medium text-text-secondary/80 transition-all duration-300 hover:text-warm-peach hover:underline underline-offset-4 decoration-warm-peach/30">
          了解更多
        </a>
      </div>

      <!-- Specs bar (desktop) -->
      <div ref="specsRef" class="mt-28 hidden sm:flex items-center justify-center gap-16">
        <div class="text-center">
          <div class="text-5xl sm:text-6xl font-extrabold text-gradient-warm tabular-nums font-mono tracking-tighter">
            {{ countUp.projects }}
          </div>
          <p class="mt-2.5 text-[11px] text-text-tertiary uppercase tracking-[0.2em] font-semibold">项目</p>
        </div>
        <div class="h-12 w-px bg-white/[0.08]" />
        <div class="text-center">
          <div class="text-5xl sm:text-6xl font-extrabold text-gradient-warm tabular-nums font-mono tracking-tighter">
            10–20
          </div>
          <p class="mt-2.5 text-[11px] text-text-tertiary uppercase tracking-[0.2em] font-semibold">天</p>
        </div>
        <div class="h-12 w-px bg-white/[0.08]" />
        <div class="text-center">
          <div class="text-5xl sm:text-6xl font-extrabold text-gradient-warm tabular-nums font-mono tracking-tighter">
            ≤¥500
          </div>
          <p class="mt-2.5 text-[11px] text-text-tertiary uppercase tracking-[0.2em] font-semibold">每套</p>
        </div>
      </div>

      <!-- Mobile specs -->
      <div class="mt-14 flex sm:hidden items-center justify-center gap-5 text-[13px] text-text-tertiary">
        <span class="font-mono"><span class="text-gradient-warm font-bold">{{ countUp.projects }}</span> 项目</span>
        <span class="text-white/[0.10]">·</span>
        <span class="font-mono"><span class="text-gradient-warm font-bold">10–20</span> 天</span>
        <span class="text-white/[0.10]">·</span>
        <span class="font-mono"><span class="text-gradient-warm font-bold">≤¥500</span>/套</span>
      </div>
    </div>

    <!-- Scroll indicator -->
    <div ref="scrollIndicatorRef" class="absolute bottom-10 left-1/2 -translate-x-1/2">
      <div class="flex flex-col items-center gap-2.5">
        <div class="scroll-line h-10 w-px bg-gradient-to-b from-text-tertiary/50 to-transparent" />
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue'
import { gsap } from 'gsap'

// ── Refs ──
const sectionRef = ref<HTMLElement | null>(null)
const bgLayer1 = ref<HTMLElement | null>(null)
const bgLayer2 = ref<HTMLElement | null>(null)
const bgLayer3 = ref<HTMLElement | null>(null)
const eyebrowRef = ref<HTMLElement | null>(null)
const titleRef = ref<HTMLElement | null>(null)
const subtitleRef = ref<HTMLElement | null>(null)
const ctaRef = ref<HTMLElement | null>(null)
const ctaBtnRef = ref<HTMLElement | null>(null)
const specsRef = ref<HTMLElement | null>(null)
const scrollIndicatorRef = ref<HTMLElement | null>(null)

// ── Count-up state (RAF) ──
const countUp = reactive({ projects: 0 })
let rafId: number | null = null

// ── Magnetic CTA ──
const magnetic = ref({ x: 0, y: 0 })

function onCtaMouseMove(e: MouseEvent) {
  if (!ctaBtnRef.value) return
  const rect = ctaBtnRef.value.getBoundingClientRect()
  const cx = rect.left + rect.width / 2
  const cy = rect.top + rect.height / 2
  magnetic.value.x = (e.clientX - cx) * 0.25
  magnetic.value.y = (e.clientY - cy) * 0.25
  gsap.to(ctaBtnRef.value, { x: magnetic.value.x, y: magnetic.value.y, duration: 0.4, ease: 'power2.out' })
}

function onCtaMouseLeave() {
  gsap.to(ctaBtnRef.value, { x: 0, y: 0, duration: 0.6, ease: 'elastic.out(1, 0.4)' })
}

// ── Parallax on scroll ──
let scrollHandler: (() => void) | null = null

function setupParallax() {
  scrollHandler = () => {
    const scrollY = window.scrollY
    const vh = window.innerHeight
    if (scrollY > vh * 1.5) return
    const progress = scrollY / vh
    gsap.set(bgLayer2.value, { y: progress * 40 })
    gsap.set(bgLayer3.value, { y: progress * 60 })
  }
  window.addEventListener('scroll', scrollHandler, { passive: true })
}

// ── Main timeline ──
let tl: gsap.core.Timeline | null = null

onMounted(() => {
  // Get title lines
  const lines = titleRef.value?.querySelectorAll('[data-split-line]') || []

  // Set initial states
  gsap.set(eyebrowRef.value, { opacity: 0, y: 20 })
  gsap.set(lines, { opacity: 0, y: 50 })
  gsap.set(subtitleRef.value, { opacity: 0, y: 25 })
  gsap.set(ctaRef.value, { opacity: 0, y: 25 })
  gsap.set(specsRef.value, { opacity: 0, y: 20 })
  gsap.set(scrollIndicatorRef.value, { opacity: 0 })

  // Build timeline
  tl = gsap.timeline({ delay: 0.3 })

  tl.to(eyebrowRef.value, {
    opacity: 1,
    y: 0,
    duration: 0.8,
    ease: 'power3.out',
  })
  .to(lines, {
    opacity: 1,
    y: 0,
    duration: 0.9,
    stagger: 0.15,
    ease: 'power3.out',
  }, '-=0.3')
  .to(subtitleRef.value, {
    opacity: 1,
    y: 0,
    duration: 0.9,
    ease: 'power3.out',
  }, '-=0.4')
  .to(ctaRef.value, {
    opacity: 1,
    y: 0,
    duration: 0.8,
    ease: 'power3.out',
  }, '-=0.35')
  .to(specsRef.value, {
    opacity: 1,
    y: 0,
    duration: 0.8,
    ease: 'power3.out',
    onStart: startCountUp,
  }, '-=0.3')
  .to(scrollIndicatorRef.value, {
    opacity: 0.3,
    duration: 1,
    ease: 'power2.out',
  }, '-=0.2')

  // Scroll indicator float
  gsap.to('.scroll-line', {
    y: 4,
    duration: 1.8,
    ease: 'sine.inOut',
    yoyo: true,
    repeat: -1,
  })

  // Magnetic CTA
  ctaBtnRef.value?.addEventListener('mousemove', onCtaMouseMove)
  ctaBtnRef.value?.addEventListener('mouseleave', onCtaMouseLeave)

  // Parallax
  setupParallax()
})

// ── RAF count-up ──
function startCountUp() {
  const duration = 2200
  const start = performance.now()
  function tick(now: number) {
    const progress = Math.min((now - start) / duration, 1)
    const eased = 1 - Math.pow(2, -10 * progress)
    countUp.projects = Math.floor(eased * 9)
    if (progress < 1) {
      rafId = requestAnimationFrame(tick)
    }
  }
  rafId = requestAnimationFrame(tick)
}

onUnmounted(() => {
  tl?.kill()
  if (rafId !== null) cancelAnimationFrame(rafId)
  ctaBtnRef.value?.removeEventListener('mousemove', onCtaMouseMove)
  ctaBtnRef.value?.removeEventListener('mouseleave', onCtaMouseLeave)
  if (scrollHandler) window.removeEventListener('scroll', scrollHandler)
})
</script>

<style scoped>
@keyframes gradientShift {
  0%, 100% {
    transform: scale(1) translate(0, 0);
    opacity: 1;
  }
  50% {
    transform: scale(1.05) translate(1%, -1%);
    opacity: 0.85;
  }
}

.noise {
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
  background-repeat: repeat;
  background-size: 256px 256px;
}
</style>
