// website/components/project-card.tsx
"use client"

/**
 * 项目卡片 — Apple App Store 风格
 *
 * 设计理念:
 * - 更大的视觉空间，更少的装饰
 * - 封面区有微妙的渐变而非纯色块
 * - 项目编号作为精致的 eyebrow
 * - 难度用小色点，不用 badge
 * - 标签更小更精致
 * - hover 时整个卡片微微提升
 */
import Link from "next/link"
import { motion } from "framer-motion"
import { ArrowUpRight, Clock, Coins } from "lucide-react"
import { type Project, getDifficultyBg } from "@/lib/projects-data"
import { cn } from "@/lib/utils"

interface ProjectCardProps {
  project: Project
  index: number
  featured?: boolean
}

export function ProjectCard({ project, index, featured = false }: ProjectCardProps) {
  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{ duration: 0.4, delay: index * 0.05 }}
    >
      <Link href={`/projects/${project.slug}`} className="block group">
        <div className={`card-glow h-full rounded-2xl border border-white/[0.10] bg-white/[0.03] overflow-hidden ${featured ? 'md:flex' : ''}`}>
          {/* 封面 — PCB 走线风格几何图案 */}
          <div
            className={`relative ${featured ? 'md:w-3/5 aspect-[16/9] md:aspect-auto' : 'aspect-[16/10]'} w-full flex items-center justify-center overflow-hidden`}
            style={{
              background: `linear-gradient(145deg, ${project.colorHex}12 0%, ${project.colorHex}06 50%, ${project.colorHex}02 100%)`,
            }}
          >
            {/* PCB 网格背景 */}
            <div
              className="absolute inset-0 opacity-[0.08]"
              style={{
                backgroundImage: `
                  linear-gradient(${project.colorHex}15 1px, transparent 1px),
                  linear-gradient(90deg, ${project.colorHex}15 1px, transparent 1px)
                `,
                backgroundSize: '32px 32px',
              }}
            />

            {/* PCB 走线装饰 */}
            <svg className="absolute inset-0 w-full h-full opacity-[0.06]" fill="none">
              <line x1="10%" y1="20%" x2="40%" y2="20%" stroke={project.colorHex} strokeWidth="1.5" />
              <line x1="40%" y1="20%" x2="40%" y2="60%" stroke={project.colorHex} strokeWidth="1.5" />
              <line x1="40%" y1="60%" x2="70%" y2="60%" stroke={project.colorHex} strokeWidth="1.5" />
              <line x1="70%" y1="60%" x2="70%" y2="35%" stroke={project.colorHex} strokeWidth="1.5" />
              <circle cx="10%" cy="20%" r="3" fill={project.colorHex} />
              <circle cx="70%" cy="35%" r="3" fill={project.colorHex} />
            </svg>

            {/* 项目编号 — Apple 式精致标签 */}
            <div className="absolute top-4 left-4">
              <span
                className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold font-mono tracking-wide"
                style={{
                  backgroundColor: `${project.colorHex}20`,
                  color: project.colorHex,
                }}
              >
                <span
                  className="h-1.5 w-1.5 rounded-full"
                  style={{ backgroundColor: project.colorHex }}
                />
                P{project.id}
              </span>
            </div>

            {/* 中心 — 项目英文代号 */}
            <span
              className={`font-mono font-bold tracking-tighter select-none ${featured ? 'text-6xl md:text-7xl opacity-[0.10]' : 'text-5xl sm:text-6xl opacity-[0.10]'}`}
              style={{ color: project.colorHex }}
            >
              {project.titleEn}
            </span>

            {/* 右上角难度 */}
            <div className="absolute top-4 right-4">
              <span
                className={cn(
                  "rounded-full px-2.5 py-1 text-[11px] font-medium",
                  getDifficultyBg(project.difficulty)
                )}
              >
                {project.difficultyLabel}
              </span>
            </div>
          </div>

          {/* 内容区 — 更多留白 */}
          <div className={`${featured ? 'md:w-2/5 md:p-8' : 'p-5 sm:p-6'} flex flex-col`}>
            {/* 项目名称 */}
            <h3 className={`${featured ? 'text-xl md:text-2xl' : 'text-[15px] sm:text-base'} font-semibold tracking-tight text-text-primary`}>
              {project.titleZh}
            </h3>
            <p className={`mt-1 ${featured ? 'text-[14px]' : 'text-[13px] sm:text-sm'} text-text-secondary`}>
              {project.subtitle}
            </p>

            {/* 参数行 — Apple 式精致图标 */}
            <div className="mt-3 flex items-center gap-4 text-[12px] text-text-tertiary">
              <span className="flex items-center gap-1.5">
                <Clock size={11} className="opacity-60" />
                {project.duration}{project.durationUnit}
              </span>
              <span className="flex items-center gap-1.5">
                <Coins size={11} className="opacity-60" />
                {project.cost}
              </span>
            </div>

            {/* 技术标签 — 精选 2-3 个最关键的 */}
            {project.tags.length > 0 && (
              <div className="mt-4 flex flex-wrap gap-1.5">
                {project.tags.slice(0, featured ? 4 : 3).map((tag) => (
                  <span
                    key={tag.label}
                    className="rounded-full px-2 py-0.5 text-[11px] font-medium bg-white/[0.05] text-text-secondary"
                  >
                    {tag.label}
                  </span>
                ))}
              </div>
            )}

            {/* 箭头 — Apple 式的微妙提示 */}
            <div className="mt-auto pt-4 flex items-center justify-end">
              <ArrowUpRight
                size={featured ? 18 : 14}
                className="text-text-tertiary/50 transition-all duration-200 group-hover:text-accent-primary group-hover:translate-x-0.5 group-hover:-translate-y-0.5"
              />
            </div>
          </div>
        </div>
      </Link>
    </motion.div>
  )
}

// website/components/ProjectCard.vue
<template>
  <TiltCard :max-tilt="6" :glare-opacity="0.08" glow="cool">
    <NuxtLink :to="`/projects/${project.slug}`" class="block group">
      <div
        ref="cardRef"
        class="spotlight relative w-[320px] sm:w-[360px] rounded-[1.75rem] overflow-hidden transition-all duration-500"
        :style="{
          background: cardGradient,
          '--glow-cool': glowRgb(project.colorHex),
          boxShadow: isHovered
            ? '0 10px 40px rgba(0,0,0,0.35), 0 0 0 1px ' + project.colorHex + '40'
            : '0 2px 8px rgba(0,0,0,0.18), 0 8px 32px rgba(0,0,0,0.22)',
          border: '1px solid ' + project.colorHex + '20',
        }"
        @mouseenter="isHovered = true"
        @mouseleave="isHovered = false"
      >
        <!-- Top area with subtle gradient + watermark -->
        <div class="relative aspect-[4/3] flex items-center justify-center overflow-hidden px-6 pt-6">
          <div class="absolute inset-0" :style="{ background: `linear-gradient(180deg, ${project.colorHex}18 0%, ${project.colorHex}06 50%, transparent 100%)` }" />

          <!-- Large project number watermark -->
          <span
            class="absolute font-mono font-bold leading-none select-none pointer-events-none transition-transform duration-700"
            :style="{
              color: project.colorHex,
              opacity: 0.13,
              fontSize: 'clamp(7rem, 14vw, 10rem)',
              letterSpacing: '-0.06em',
              top: '-0.1em',
              right: '-0.05em',
              transform: isHovered ? 'scale(1.05) translateX(2px)' : 'scale(1)',
            }"
          >
            {{ project.id }}
          </span>

          <!-- Project ID pill -->
          <div class="absolute top-5 left-5 z-[2]">
            <span
              class="inline-flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-[11px] font-bold font-mono tracking-wide backdrop-blur-md"
              :style="{ backgroundColor: `${project.colorHex}20`, color: project.colorHex }"
            >
              <span class="h-1.5 w-1.5 rounded-full" :style="{ backgroundColor: project.colorHex }" />
              P{{ project.id }}
            </span>
          </div>

          <!-- Difficulty pill -->
          <div class="absolute top-5 right-5 z-[2]">
            <span
              class="rounded-full px-3 py-1.5 text-[11px] font-semibold backdrop-blur-md"
              :style="{ backgroundColor: `${difficultyColor}20`, color: difficultyColor }"
            >
              {{ project.difficultyLabel }}
            </span>
          </div>

          <!-- MCU label centered -->
          <div class="relative z-[1] flex flex-col items-center gap-3 text-center">
            <div
              class="flex h-16 w-16 items-center justify-center rounded-2xl transition-transform duration-500 group-hover:scale-110"
              :style="{
                background: `linear-gradient(145deg, ${project.colorHex}30, ${project.colorHex}10)`,
                backdropFilter: 'blur(12px)',
                border: `1px solid ${project.colorHex}20`,
              }"
            >
              <span class="text-lg font-bold font-mono" :style="{ color: project.colorHex }">
                {{ project.mcu.split('-')[0] }}
              </span>
            </div>
            <span class="text-[12px] font-mono text-text-tertiary tracking-wider">{{ project.coreTech }}</span>
          </div>
        </div>

        <!-- Content -->
        <div class="relative px-6 pb-6 pt-2">
          <!-- Subtle separator line -->
          <div class="absolute top-0 left-6 right-6 h-px" :style="{ background: `linear-gradient(90deg, transparent, ${project.colorHex}25, transparent)` }" />

          <!-- Title -->
          <h3
            class="text-[18px] font-bold tracking-tight text-text-primary transition-colors duration-300 group-hover:text-text-primary"
          >
            {{ project.titleZh }}
          </h3>
          <p class="mt-1.5 text-[13px] text-text-secondary leading-relaxed line-clamp-2">
            {{ project.subtitle }}
          </p>

          <!-- Duration & cost -->
          <div class="mt-4 flex items-center gap-5 text-[12px] text-text-tertiary bg-white/[0.02] rounded-xl px-3 py-1.5 -mx-3">
            <span class="flex items-center gap-1.5">
              <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="opacity-60">
                <circle cx="12" cy="12" r="10" />
                <polyline points="12 6 12 12 16 14" />
              </svg>
              {{ project.duration }}{{ project.durationUnit }}
            </span>
            <span class="flex items-center gap-1.5">
              <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="opacity-60">
                <path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
              </svg>
              {{ project.cost }}
            </span>
          </div>

          <!-- Color tags -->
          <div class="mt-4 flex flex-wrap gap-1.5">
            <span
              v-for="tag in project.tags.slice(0, 3)"
              :key="tag.label"
              class="rounded-full px-2.5 py-0.5 text-[11px] font-semibold transition-colors duration-300"
              :style="{
                backgroundColor: `${project.colorHex}20`,
                color: project.colorHex,
                border: `1px solid ${project.colorHex}25`,
              }"
            >
              {{ tag.label }}
            </span>
          </div>

          <!-- Arrow -->
          <div class="mt-5 flex items-center justify-between">
            <span class="text-[11px] text-text-faint transition-colors duration-300 group-hover:text-text-tertiary">查看详情</span>
            <div
              class="flex h-9 w-9 items-center justify-center rounded-full transition-all duration-300 text-text-tertiary group-hover:text-white group-hover:scale-110"
              :style="{ backgroundColor: isHovered ? project.colorHex : 'rgba(255,255,255,0.04)' }"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M7 7h10v10" />
                <path d="M7 17 17 7" />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </NuxtLink>
  </TiltCard>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Project } from '~/content/projects'
import TiltCard from './TiltCard.vue'
import { useSpotlight } from '~/composables/useSpotlight'

const props = defineProps<{
  project: Project
}>()

const isHovered = ref(false)
const cardRef = ref<HTMLElement | null>(null)
useSpotlight(cardRef, { glow: 'cool' })

// Map a hex accent to "r, g, b" so the .spotlight follow-light tints to the card's own accent
function glowRgb(hex: string): string {
  const h = hex.replace('#', '')
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  return `${r}, ${g}, ${b}`
}

const difficultyColor = computed(() => {
  const colors: Record<number, string> = {
    1: '#3d8b5e',
    2: '#3d8b5e',
    3: '#c9944a',
    4: '#ff9a76',
    5: '#ff6b6b',
  }
  return colors[props.project.difficulty] || '#c9944a'
})

const cardGradient = computed(() => {
  const hex = props.project.colorHex
  return `linear-gradient(160deg, ${hex}22 0%, ${hex}0a 35%, #0b0d12 100%)`
})
</script>
