// website/components/TestimonialsSection.vue
<template>
  <section id="testimonials" class="section-dark py-24 md:py-36 lg:py-44">
    <div class="mx-auto max-w-4xl px-6">
      <div class="mb-20 text-center">
        <p class="eyebrow mb-4">学员反馈</p>
        <h2 class="text-section font-bold tracking-tight text-text-primary">他们的第一次</h2>
      </div>

      <!-- Quote -->
      <div class="text-center">
        <div class="mb-6">
          <span class="text-6xl sm:text-7xl md:text-8xl font-serif leading-none text-gradient-warm">"</span>
        </div>

        <Transition name="testimonial" mode="out-in">
          <blockquote :key="activeIndex" class="text-2xl sm:text-3xl md:text-4xl leading-snug font-semibold text-text-primary tracking-tight">
            {{ testimonials[activeIndex].quote }}
          </blockquote>
        </Transition>

        <Transition name="testimonial" mode="out-in">
          <div :key="'author-' + activeIndex" class="mt-10 flex items-center justify-center gap-3">
            <div class="flex h-11 w-11 items-center justify-center rounded-full text-[15px] font-semibold"
              style="background: linear-gradient(135deg, #ff9a7630, #ff6b6b30); color: #ff9a76;">
              {{ testimonials[activeIndex].name[0] }}
            </div>
            <div class="text-[14px]">
              <span class="font-medium text-text-primary">{{ testimonials[activeIndex].name }}</span>
              <span class="text-text-tertiary"> · {{ testimonials[activeIndex].grade }}</span>
              <span class="text-text-tertiary"> · </span>
              <NuxtLink :to="`/projects/${testimonials[activeIndex].slug}`" class="text-warm-peach hover:text-warm-coral transition-colors duration-200">{{ testimonials[activeIndex].project }}</NuxtLink>
            </div>
          </div>
        </Transition>

        <!-- Dots -->
        <div class="mt-10 flex items-center justify-center gap-2">
          <button v-for="(_, i) in testimonials" :key="i"
            @click="setTestimonial(i)"
            :class="[
              'h-2 rounded-full transition-all duration-300',
              activeIndex === i ? 'w-8 bg-warm-peach' : 'w-2 bg-white/[0.15] hover:bg-white/[0.25]'
            ]"
            :aria-label="`查看第 ${i+1} 条评价`" />
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const activeIndex = ref(0)
let interval: ReturnType<typeof setInterval> | null = null
let userInteracted = false
let resumeTimeout: ReturnType<typeof setTimeout> | null = null

const testimonials = [
  { name: '张同学', grade: '高一', project: '天气魔方', slug: 'weather-cube', quote: '第一次自己焊接电路板，虽然手抖了好几次，但看到 OLED 屏幕亮起来的时候超有成就感。' },
  { name: '王同学', grade: '高一', project: '轮足机器人', slug: 'bipedal-wheeled-robot', quote: 'PID 调参真的会上头，调了两天终于让机器人站起来了。物理课学的控制理论终于派上用场。' },
  { name: '赵同学', grade: '高三', project: 'ElectronBot', slug: 'electronbot', quote: '这个项目让我确定了大学要学电子工程。从 PCB 到 Unity 上位机，真正体验了全栈开发。' },
  { name: '李同学', grade: '高二', project: '四模键盘', slug: '4mode-keyboard', quote: '从画原理图到焊四层板，最后敲出第一个字的时候感觉像变魔术一样。原来键盘后面这么复杂。' },
  { name: '陈同学', grade: '高一', project: '桌宠机器人', slug: 'desktop-pet', quote: '给小机器人接上 AI 大脑之后，它居然能听懂我说话了。室友们都抢着跟它聊天。' },
]

function setTestimonial(index: number) {
  activeIndex.value = index
  userInteracted = true
  if (resumeTimeout) clearTimeout(resumeTimeout)
  resumeTimeout = setTimeout(() => { userInteracted = false }, 8000)
}

onMounted(() => {
  interval = setInterval(() => {
    if (!userInteracted) {
      activeIndex.value = (activeIndex.value + 1) % testimonials.length
    }
  }, 5000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
  if (resumeTimeout) clearTimeout(resumeTimeout)
})
</script>

<style scoped>
.testimonial-enter-active,
.testimonial-leave-active {
  transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
}

.testimonial-enter-from {
  opacity: 0;
  transform: translateY(12px);
}

.testimonial-leave-to {
  opacity: 0;
  transform: translateY(-8px);
}
</style>

// website/components/testimonials-section.tsx
"use client"

/**
 * 学员评价 Section — Apple Customer Story 大引言风格
 *
 * 设计理念:
 * - 只展示 3 条精选引言，不再是均匀网格
 * - 第一个大引言占满整行
 * - 第二第三个并排显示
 * - 大号引言文字 (24-32px)，如 Apple pull quote
 */
import { motion } from "framer-motion"

const testimonials = [
  {
    name: "张同学",
    grade: "高一",
    project: "天气魔方",
    quote: "第一次自己焊接电路板，虽然手抖了好几次，但看到 OLED 屏幕亮起来的时候超有成就感。",
    featured: true,
  },
  {
    name: "王同学",
    grade: "高一",
    project: "轮足机器人",
    quote: "PID 调参真的很上头，调了两天终于让机器人站起来了。物理课学的控制理论终于派上用场。",
  },
  {
    name: "赵同学",
    grade: "高三",
    project: "ElectronBot",
    quote: "这个项目让我确定了大学要学电子工程。从 PCB 到 Unity 上位机，真正体验了全栈开发。",
  },
]

export function TestimonialsSection() {
  return (
    <section id="testimonials" className="section-dark py-24 md:py-36 lg:py-44">
      <div className="mx-auto max-w-5xl px-6">
        {/* Apple 式 eyebrow + 大标题 */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          className="mb-20 text-center"
        >
          <p className="eyebrow mb-4">学员反馈</p>
          <h2 className="text-responsive-section font-bold tracking-tight text-text-primary">
            他们的第一次
          </h2>
        </motion.div>

        {/* 大引言 — 精选首条 */}
        <FeaturedQuote testimonial={testimonials[0]} />

        {/* 小引言 — 其余两条并排 */}
        <div className="mt-6 grid gap-5 sm:grid-cols-2">
          {testimonials.slice(1).map((t, i) => (
            <QuoteCard key={t.name} testimonial={t} delay={0.1 + i * 0.1} />
          ))}
        </div>
      </div>
    </section>
  )
}

function FeaturedQuote({ testimonial }: { testimonial: typeof testimonials[0] }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
      className="rounded-2xl bg-white/[0.03] p-8 md:p-12"
    >
      {/* 大引言文字 */}
      <blockquote className="text-[20px] sm:text-[24px] md:text-[28px] leading-snug font-medium text-text-primary tracking-tight">
        &ldquo;{testimonial.quote}&rdquo;
      </blockquote>

      {/* 人物信息 */}
      <div className="mt-8 flex items-center gap-3">
        <div
          className="flex h-10 w-10 items-center justify-center rounded-full text-[14px] font-semibold"
          style={{
            background: "linear-gradient(135deg, #c9944a30, #3d8b5e30)",
            color: "#c9944a",
          }}
        >
          {testimonial.name[0]}
        </div>
        <div className="text-[14px]">
          <span className="font-medium text-text-primary">{testimonial.name}</span>
          <span className="text-text-tertiary"> · {testimonial.grade} · {testimonial.project}</span>
        </div>
      </div>
    </motion.div>
  )
}

function QuoteCard({ testimonial, delay }: { testimonial: typeof testimonials[0]; delay: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.6, delay }}
      className="card-glow rounded-2xl border border-white/[0.10] bg-white/[0.03] p-6 sm:p-7"
    >
      <blockquote className="text-[15px] sm:text-[16px] leading-relaxed text-text-secondary/90">
        &ldquo;{testimonial.quote}&rdquo;
      </blockquote>

      <div className="mt-5 flex items-center gap-3">
        <div
          className="flex h-8 w-8 items-center justify-center rounded-full text-[12px] font-semibold"
          style={{
            background: "linear-gradient(135deg, #c9944a30, #3d8b5e30)",
            color: "#c9944a",
          }}
        >
          {testimonial.name[0]}
        </div>
        <div className="text-[13px]">
          <span className="font-medium text-text-primary">{testimonial.name}</span>
          <span className="text-text-tertiary"> · {testimonial.grade} · {testimonial.project}</span>
        </div>
      </div>
    </motion.div>
  )
}
